### ISSUE TITLE
New pallets implementation

### ISSUE THREAD

**Issue by 3Dpass** [3Dpass/3DP#19]
Implement the following pallets into Runtime: 
1. [Session](https://github.com/paritytech/substrate/tree/master/frame/session)
2. [Smart Contracts](https://github.com/paritytech/substrate/tree/master/frame/contracts)
3. [Democracy](https://github.com/paritytech/substrate/tree/master/frame/democracy)
4. [Multisig](https://github.com/paritytech/substrate/tree/master/frame/multisig)

**Comment by PaulSff** [comment]
Done: https://github.com/3Dpass/3DP/commit/6436156d23c710ca6f0dc6729c690e2f3a4b000f

**Comment by PaulSff** [comment]
Additional pallets: 
- RandomnessCollectiveFlip
- Timestamp
- Scheduler
- Preimage
- Indices
- Rewards
- Balances
- Authorship
- TransactionPayment
- Democracy
- Remark
- Council
- TechnicalCommittee
- Treasury
- Multisig
- TransactionStorage
- Uniques
- Assets
- Bounties
- ChildBounties
- Identity
- Vesting
- Contracts
- ScoredPool
- ValidatorSet
- Session
