### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by ricohrh** [3Dpass/3DP#22]
i  use dorker 

miner  | Error: connect ECONNREFUSED 172.18.0.2:9933
node   | Error: Input("Invalid seed: InvalidFormat")
miner  | Error: connect ECONNREFUSED 172.18.0.2:9933
node   | 2022-07-24 07:58:04 Proof Of Scan Consensus Node (PoScan and Grandpa)    
node   | 2022-07-24 07:58:04 ✌️  version 3.0.0-unknown-x86_64-linux-gnu    
node   | 2022-07-24 07:58:04 ❤️  by Substrate DevHub <https://github.com/substrate-developer-hub>, 2019-2022    
node   | 2022-07-24 07:58:04 📋 Chain specification: 3DP testnet    
node   | 2022-07-24 07:58:04 🏷 Node name: old-agreement-4125    
node   | 2022-07-24 07:58:04 👤 Role: AUTHORITY    
node   | 2022-07-24 07:58:04 💾 Database: RocksDb at /var/chain/chains/3dp/db    
node   | 2022-07-24 07:58:04 ⛓  Native runtime: poscan-runtime-1 (poscan-runtime-1.tx1.au1)    
node   | 2022-07-24 07:58:04 🏷 Local node identity is: 12D3KooWJhwrfhG89ME27p6UrCtp4LmHi8heDrZGVga73JYj2CPc    
node   | 2022-07-24 07:58:04 📦 Highest known block at #0    
node   | 2022-07-24 07:58:04 〽️ Prometheus server started at 127.0.0.1:9615    
node   | 2022-07-24 07:58:04 Listening for new connections on 0.0.0.0:9944.    
node   | Error: Service(Other("Invalid author address"))
miner  | Error: getaddrinfo ENOTFOUND node

why get this error message

**Comment by fedosov** [comment]
Probably you have provided an invalid seed phrase in `docker-compose.override.yml`, please follow the instruction: https://github.com/3Dpass/3DP#mining-with-docker
