### ISSUE TITLE
Increase the complexity of the generated 3D model

### ISSUE THREAD

**Issue by ndcc5** [3Dpass/3DP#32]
Increase the complexity of the generated 3D model. As there are more and more 3D models, the prompt ">>> duplicate hashes found more and more frequently.

**Comment by fedosov** [comment]
You are free to open a Pull Request with desired modifications for the miner!

**Comment by ndcc5** [comment]
My friend, not every miner is a programmer.💔

**Comment by fedosov** [comment]
You are right; I will keep this issue open and see what we can do. Thank you!

**Comment by PaulSff** [comment]
In my opinion, this kind of issues take our focus away from the general lane we should stick around. So, it doesn't make sense to carry it out on the team's budget. If miners would like us to hire additional members who is to maintain and improve mining tools, should then they provide budget for that.

**Comment by ndcc5** [comment]
> In my opinion, this kind of issues take our focus away from the general lane we should stick around. So, it doesn't make sense to carry it out on the team's budget. If miners would like us to hire additional members who is to maintain and improve mining tools, should then they provide budget for that.

I don't think so, if a miner successfully optimizes the 3D model generation, he mines 90% of the 3dp tokens, do you think this is good or bad for this project? It is best for the official to solve the mining problem. Don’t expect the things optimized by a miner to be easily shared with other miners.

**Comment by PaulSff** [comment]
> I don't think so, if a miner successfully optimizes the 3D model generation, he mines 90% of the 3dp tokens, do you think this is good or bad for this project? It is best for the official to solve the mining problem. Don’t expect the things optimized by a miner to be easily shared with other miners.

 If someone invested into the mining optimization he's been taking all the advantages of it. If someone didn't and doesn't want to, why someone else should?

**Comment by PaulSff** [comment]
Everyone is welcome to contribute on this issue.

**Comment by PaulSff** [comment]
Done: https://github.com/3Dpass/3DP/commit/40700e26478a5621b2276d20dd3fd7e560feb0cf
