### ISSUE TITLE
Thread main panicked on initial install

### ISSUE THREAD

**Issue by nomadic-coding** [3Dpass/3DP#65]
After running command:
`cargo run --release -- --dev --tmp`
the following output is produced:

> Finished release [optimized] target(s) in 5m 16s
> warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.2.0, nalgebra v0.27.1
> note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
>      Running `target/release/poscan-consensus --dev --tmp`
> 
> ====================
> 
> Version: 3.1.0-79caf1b-x86_64-linux-gnu
> 
>    0: sp_panic_handler::set::{{closure}}
>    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/alloc/src/boxed.rs:1999:9
>       std::panicking::rust_panic_with_hook
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:695:13
>    2: std::panicking::begin_panic_handler::{{closure}}
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:580:13
>    3: std::sys_common::backtrace::__rust_end_short_backtrace
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/sys_common/backtrace.rs:151:18
>    4: rust_begin_unwind
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:578:5
>    5: core::panicking::panic_fmt
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/core/src/panicking.rs:67:14
>    6: <pallet_validator_set::pallet::GenesisConfig<T> as frame_support::traits::hooks::GenesisBuild<T>>::build
>    7: environmental::using
>    8: sp_state_machine::basic::BasicExternalities::execute_with_storage
>    9: <poscan_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
>   10: sp_runtime::BuildStorage::build_storage
>   11: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sp_runtime::BuildStorage>::build_storage
>   12: sc_service::client::client::Client<B,E,Block,RA>::new
>   13: sc_service::builder::new_full_parts
>   14: poscan_consensus::service::new_partial
>   15: poscan_consensus::service::new_full
>   16: tokio::park::thread::CachedParkThread::block_on
>   17: tokio::runtime::thread_pool::ThreadPool::block_on
>   18: tokio::runtime::Runtime::block_on
>   19: sc_cli::runner::Runner<C>::run_node_until_exit
>   20: poscan_consensus::command::run
>   21: poscan_consensus::main
>   22: std::sys_common::backtrace::__rust_begin_short_backtrace
>   23: std::rt::lang_start::{{closure}}
>   24: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/core/src/ops/function.rs:284:13
>       std::panicking::try::do_call
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:485:40
>       std::panicking::try
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:449:19
>       std::panic::catch_unwind
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panic.rs:142:14
>       std::rt::lang_start_internal::{{closure}}
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/rt.rs:148:48
>       std::panicking::try::do_call
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:485:40
>       std::panicking::try
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:449:19
>       std::panic::catch_unwind
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panic.rs:142:14
>       std::rt::lang_start_internal
>              at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/rt.rs:148:20
>   25: main
>   26: <unknown>
>   27: __libc_start_main
>   28: _start
> 
> 
> Thread 'main' panicked at 'Initial set of validators must be at least T::MinAuthorities', /root/3DP/pallets/validator-set/src/lib.rs:672
> 
> This is a bug. Please report it at:
> 
>         https://github.com/3Dpass/3DP/issues

**Comment by PaulSff** [comment]
Hello, it looks the same to this one: https://github.com/3Dpass/3DP/issues/64#issuecomment-1754790706
