### ISSUE TITLE
Node running error.

### ISSUE THREAD

**Issue by blue-skyyy** [3Dpass/3DP#66]
After the node running. 

gagein@gagein-desktop:~/3DP$ ./target/release/poscan-consensus --base-path ~/3dp-chain/ --chain mainnetSpecRaw.json --name gagein --validator --telemetry-url "wss://submit.telemetry.3dpscan.io/submit 0" --author 0x6274c90adbfc454a4211af91abfef1eb9ffe3bec01d548c0b0ec89c4a65f6b0f --threads 2 --no-mdns

2023-11-06 10:38:30 〽️ Prometheus exporter started at 127.0.0.1:9615    
2023-11-06 10:38:31 🔍 Discovered new external address for our node: /ip4/121.144.209.220/tcp/30333/p2p/12D3KooWSiJ3RET8wPmVLsXxkzeAopd47PAb9FpYLaD2kDS5Gh8F    

====================

Version: 3.1.0-79caf1b-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/alloc/src/boxed.rs:1999:9
      std::panicking::rust_panic_with_hook
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:695:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:582:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/sys_common/backtrace.rs:151:18
   4: rust_begin_unwind
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:578:5
   5: core::panicking::panic_fmt
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/core/src/panicking.rs:67:14
   6: core::panicking::panic_bounds_check
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/core/src/panicking.rs:162:5
   7: p3d::algo_grid::get_contour
   8: p3d::p3d_process_n
   9: poscan_algo::get_obj_hashes_n
  10: poscan_algo::get_obj_hashes
  11: <poscan_grid2d::PoscanAlgorithm<C> as sc_consensus_poscan::PowAlgorithm<B>>::verify
  12: <sc_consensus_poscan::PowBlockImport<B,I,C,S,Algorithm,CAW,CIDP> as sc_consensus::block_import::BlockImport<B>>::import_block::{{closure}}
  13: <alloc::boxed::Box<dyn sc_consensus::block_import::BlockImport<B>+Error = sp_consensus::error::Error+Transaction = Transaction+core::marker::Sync+core::marker::Send> as sc_consensus::block_import::BlockImport<B>>::import_block::{{closure}}
  14: <&mut F as core::future::future::Future>::poll
  15: sc_consensus::import_queue::basic_queue::BlockImportWorker<B>::new::{{closure}}
  16: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  17: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  18: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  19: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  20: tokio::park::thread::CachedParkThread::block_on
  21: tokio::runtime::handle::Handle::block_on
  22: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  23: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::blocking::pool::Inner::run
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/alloc/src/boxed.rs:1985:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/alloc/src/boxed.rs:1985:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/sys/unix/thread.rs:108:17
  29: start_thread
             at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  30: clone
             at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/gagein/.cargo/git/checkouts/p3d-675c372166b26a37/cfd70b0/src/algo_grid.rs:533

This is a bug. Please report it at:

	https://github.com/3Dpass/3DP/issues

**Comment by PaulSff** [comment]
Hey, check out this one: https://github.com/3Dpass/3DP/issues/64#issuecomment-1754790706
