### ISSUE TITLE
bug:docker build error

### ISSUE THREAD

**Issue by bugxzhu** [3Dpass/3DP#67]
671.7    Compiling pallet-conviction-voting v4.0.0-dev (https://github.com/paritytech/substrate?rev=b0777b4c7f7#b0777b4c)
1672.1    Compiling poscan-algo v3.0.0 (/app/consensus/poscan_algo)
1672.5    Compiling poscan-api v3.0.0 (/app/traits/poscan)
1672.5 error[E0599]: no method named `is_finished` found for struct `JoinHandle` in the current scope
1672.5    --> consensus/poscan_algo/src/lib.rs:164:15
1672.5     |
1672.5 164 |             if handler.is_finished() {
1672.5     |                        ^^^^^^^^^^^ method not found in `JoinHandle<(std::time::Duration, std::vec::Vec<sp_core::H256>)>`
1672.5 
1672.6 For more information about this error, try `rustc --explain E0599`.
1672.6 error: could not compile `poscan-algo` due to previous error
1672.6 warning: build failed, waiting for other jobs to finish...
1711.2 error: build failed

the lastest version

**Comment by bugxzhu** [comment]
=> ERROR [node builder 6/6] RUN --mount=type=cache,target=/usr/local/cargo/registry     --mount=type=cache,target=/usr/local/cargo/git       2.1s
------                                                                                                                                             
 > [node builder 6/6] RUN --mount=type=cache,target=/usr/local/cargo/registry     --mount=type=cache,target=/usr/local/cargo/git     --mount=type=cache,target=/app/target/release/build     --mount=type=cache,target=/app/target/release/deps     --mount=type=cache,target=/app/target/release/.fingerprint     --mount=type=cache,target=/app/target/release/wbuild     cargo build --release:                                                       
0.750    Compiling wasm-opt-cxx-sys v0.111.0                                                                                                       
0.751 warning: Git command failed with status: exit status: 128                                                                                    
0.751 warning: Could not find `.git/HEAD` searching from `/app/nodes/poscan-consensus` upwards!
0.751    Compiling kvdb-rocksdb v0.15.2
0.754    Compiling poscan-algo v3.0.0 (/app/consensus/poscan_algo)
0.756    Compiling pallet-bounties v4.0.0-dev (https://github.com/paritytech/substrate?rev=b0777b4c7f7#b0777b4c)
0.757    Compiling pallet-rewards v2.8.0 (/app/pallets/rewards)
0.757    Compiling pallet-grandpa v4.0.0-dev (https://github.com/paritytech/substrate?rev=b0777b4c7f7#b0777b4c)
0.760    Compiling sc-finality-grandpa-rpc v0.10.0-dev (https://github.com/paritytech/substrate?rev=b0777b4c7f7#b0777b4c)
0.877    Compiling wasm-opt v0.111.0
0.966    Compiling sc-client-db v0.10.0-dev (https://github.com/paritytech/substrate?rev=b0777b4c7f7#b0777b4c)
0.998 error[E0599]: no method named `is_finished` found for struct `JoinHandle` in the current scope
0.998    --> consensus/poscan_algo/src/lib.rs:164:15
0.998     |
0.998 164 |             if handler.is_finished() {
0.998     |                        ^^^^^^^^^^^ method not found in `JoinHandle<(std::time::Duration, std::vec::Vec<sp_core::H256>)>`
0.998 
1.026 For more information about this error, try `rustc --explain E0599`.
1.032 error: could not compile `poscan-algo` due to previous error
1.032 warning: build failed, waiting for other jobs to finish...
2.031 error: build failed
------
failed to solve: process "/bin/sh -c cargo build --release" did not complete successfully: exit code: 101

**Comment by PaulSff** [comment]
Fixed https://github.com/3Dpass/3DP/commit/16ae6b31025ac04ada9816aebb890b1aa04f9482
