### ISSUE TITLE
Poscan hash is not verified when importing blocks

### ISSUE THREAD

**Issue by TacogentP3D** [3Dpass/3DP#69]
This allows you to mine by only bruteforcing the poscan hash and submitting an unrelated object along with it, simplifying the task to just a single sha3

This can be fixed by checking it in https://github.com/3Dpass/3DP/blob/110c140a97ac8e726889ff21127adad8f907d0f6/consensus/poscan_grid2d/src/lib.rs#L158-L158

like

```rust
let dh = DoubleHash { pre_hash: *pre_hash, obj_hash: poscan_data.hashes[0] };
if dh.calc_hash() != seal.poscan_hash {
	info!(">>> verify: dh.calc_hash() != seal.poscan_hash");
	return Ok(false);
}
```

**Comment by PaulSff** [comment]
Thank you for such an important report, we'll do our best to fix it as soon as possible.
