### ISSUE TITLE
Substrate-to-Substrate cross-chain bridge (3DPass testnet - 3DPass mainnet)

### ISSUE THREAD

**Issue by 3Dpass** [3Dpass/3DP#8]
**Motivation**

In order to ensure decentralized exchange testnet 3DPs (mined over the test period) for mainnet 3DPs, we need Substrate-to-Substrate cross-chain bridge to be run. 

**Suggested Solution**

We should use an Open Source existing solutions for Substrate

**Alternatives**
We can not see the reason, why we have to develop our own bridge, which is also possible. 

**Additional Information**

Research required

**Comment by PaulSff** [comment]
Implement pallets: pallet-bridge-grandpa, message delivery and message dispatch.
https://github.com/paritytech/parity-bridges-common/blob/master/docs/high-level-overview.md  

Run syncing and validate headers from testnet inside of the mainnet runtime.

**Comment by PaulSff** [comment]
After a month of testing, we decided not to use this native Substrate bridging tools based on Grandpa finalization.
